
---
platform: linux
inputs:
  - name: chat-client
outputs:
  - name: build
image_resource:
  type: docker-image
  source:
    repository: node
    tag: '10'
run:
  path: chat-client/ci/tasks/build.sh